#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
author = "Daniel Le"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Clara Halvorsen, Folketingskandidat for Radikale Venstre."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Hovedstadens Radikale Venstre: Kompagnistræde 22, 1208 København"
phone = ["+45 28494672"]
email = [""]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = false
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "KOM I KONTAKT"
link = "https://www.facebook.com/profile.php?id=100077737042472"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "VIL DU VÆRE EN DEL AF KAMPAGNEN?"
content = ""
button = "KOM I KONTAKT"
button_link = "https://www.facebook.com/profile.php?id=100077737042472"

############################# social site ########################
[[social]]
title = "FACEBOOK"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://www.facebook.com/profile.php?id=100077737042472"

[[social]]
title = "INSTAGRAM"
icon = "lab la-instagram"  # https://icons8.com/line-awesome
link = "https://www.instagram.com/clarahalvorsen/?hl=da"


[[social]]
title = "TWITTER"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "https://twitter.com/clhalv?lang=da"
