# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
white = "#ffffff"
black = "#003974"
light = "#FAFAFA"
primary_color = "#EC008C"

# EC008C

# font variable
h1 = "120px"
h1_md = "60px"
h2 = "48px"
h2_md = "30px"
h3 = "22px"
h3_md = "20px"
h4 = "18px"
h5 = "16px"
h6 = "15px"
p = "20px"
p_md = "18px"





############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"
[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"